[package]
name = "devconsole"
version = "0.1.0"
authors = ["Jason Miesionczek <atmospherian@gmail.com>"]
edition = "2018"

[dependencies]
serde_derive = "1.0.84"
serde = "1.0.84"
serde_json = "1.0.35"
colored = "1.7"